import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import Home from '../components/Home/Home'

export default function App() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Home />
      </main>
    </div>
  )
}
